// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqjgtqgytbfrqwnmnyeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxamd0cWd5dGJmcnF3bm1ueWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzU5OTYsImV4cCI6MjA2NTUxMTk5Nn0.ov6IoeL5Wi_MsGqsBpLZBpWKkBbXyotu9nR0rQLW9h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);